# See https://istio.io/latest/docs/reference/config/networking/gateway/#Gateway for spec
gateways:
  main: # This becomes the name of the gateway
    selector:
      app: "istio-ingressgateway"
    servers:  # HTTP redirect to HTTPS is automatically added
    - hosts:
      - "*.{{ .Values.domain }}"
      port:
        name: https
        number: 8443
        protocol: HTTPS
      tls:
        credentialName: "wildcard-cert"
        mode: "SIMPLE"
  # # Example of adding additional gateways
  # private:
  #   selector:
  #     app: "private-istio-ingressgateway"
  #   servers:
  #   - hosts:
  #     - "mypackage.{{ .Values.domain }}"
  #     port:
  #       name: http2
  #       number: 8443
  #       protocol: HTTPS
  #     tls:
  #       credentialName: "some-secret"
  #       mode: "SIMPLE"

values:
  global: {}
